const cityNameMap: Record<string, string> = {
  Tehran: "تهران",
  Moḩammadābād: "مشهد",
  Isfahan: "اصفهان",
  Tabriz: "تبریز",
  Paris: "پاریس",
  Lyon: "لیون",
  Marseille: "مارسی",
  Nice: "نیس",
  Berlin: "برلین",
  Mitte: "برلین",
  Munich: "مونیخ",
  Altstadt: "مونیخ",
  Hamburg: "هامبورگ",
  Neustadt: "هامبورک",
  "Altstadt Nord": "کلن",
  "New York": "نیویورک",
  "Los Angeles": "لس آنجلس",
  Chicago: "شیکاگو",
  Houston: "هوستون",
  London: "لندن",
  Manchester: "منچستر",
  Birmingham: "بیرمنگام",
  "Glasgow City": "گلاسگو",
  Beijing: "پکن",
  Shanghai: "شانگهای",
  "Shanghai Municipality": "شانگهای",
  Guangzhou: "گوانگژو",
  Shenzhen: "شنژن",
  Gangxia: "شنژن",
  Tokyo: "توکیو",
  Horinouchi: "توکیو",
  Osaka: "اوساکا",
  Shijōdōri: "کیوتو",
  Shintoku: "هوکایدو",
  Moscow: "مسکو",
  "Novaya Gollandiya": "سن پترزبورگ",
  Novosibirsk: "نووسیبیرسک",
  Yekaterinburg: "یکاترینبورگ",
  "Posëlok Rabochiy": "یکاترینبورگ",
  Toronto: "تورنتو",
  "Downtown Toronto": "تورنتو",
  Vancouver: "ونکوور",
  Sol: "مادرید",
  Gothenburg:"گوتن برگ",
  Montreal: "مونترال",
  Calgary: "کلگری",
  Sydney: "سیدنی",
  Melbourne: "ملبورن",
  Brisbane: "بریزبین",
  Perth: "پرت",
  Maylands: "پرت",
  Rome: "رم",
  Trevi: "رم",
  Milan: "میلان",
  Naples: "ناپل",
  Turin: "تورین",
  "ses Truqueries": "مادرید",
  Barcelona: "بارسلونا",
  "Sant Pere, Santa Caterina i La Ribera": "بارسلونا",
  Valencia: "والنسیا",
  Seville: "سویل",
  Brasília: "برازیلیا",
  "Rio de Janeiro": "ریودوژانیرو",
  Liberdade: "سائوپائولو",
  Salvador: "سالوادور",
  "Kanija Bhavan" : "بانگالور",
  "Parliament House, Delhi": "دهلی نو",
  "Konkan Division": "بمبئی",
  Bengaluru: "بنگلور",
  "Park Town": "چنای",
  Seoul: "سئول",
  Busan: "پوسان",
  Incheon: "اینچئون",
  Daegu: "دائگو",
  KaraköyF: "استانبول",
  Ulus: "آنکارا",
  Izmir: "ازمیر",
  Antalya: "آنتالیا",
  "Mexico City": "مکزیکو سیتی",
  Guadalajara: "گوادالاخارا",
  Monterrey: "مونتری",
  Cancún: "کانکون",
  Amsterdam: "آمستردام",
  Rotterdam: "رتردام",
  "Gemeente Den Haag": "لاهه",
  Utrecht: "اوترخت",
  Stockholm: "استکهلم",
  Nordstaden: "گوتنبرگ",
  "Gamla Staden": "مالمو",
  Uppsala: "اوپسالا",
  Malmo : "مالمو",
};

export function CityTranslate({ name }: { name: string }) {
  return cityNameMap[name] || name;
}
